### ISSUE TITLE
Get Data assignment completed 

### ISSUE THREAD

**Issue by amandavel** [amandavel/amandaresearchproject#2]
@AaronGullickson Hi Aaron, I've completed the Get Data assignment, but when I try to read in this script at the beginning of organize_data.r:
```
source("check_packages.R")
source("useful_functions.R")

```
I get this error message:
```
In file(filename, "r", encoding = encoding) :
  cannot open file 'useful_functions.R': No such file or directory
```
which is causing a chain reaction of errors in my code. I've checked and double checked the other parts of my code and can't find any errors.

Best,
Amanda

**Comment by AaronGullickson** [comment]
@amandavel You just need to set your working directory to the analysis directory before running. It works fine for me.

However, the code does break for me on your `read_fwf` line because you have never loaded the `readr` library. You need to either do that at the top of the `organized_data.R` script or add it to the list of libraries in the `check_packages.R` script.

**Comment by amandavel** [comment]
@AaronGullickson That worked! But now I have this error message:

```
Warning: 12809158 parsing failures.
row      col   expected        actual                     file
  1 cbserial an integer 2017000000016 'input/usa_00007.dat.gz'
  1 cluster  an integer 2017000000011 'input/usa_00007.dat.gz'
  2 cbserial an integer 2017000000031 'input/usa_00007.dat.gz'
  2 cluster  an integer 2017000000021 'input/usa_00007.dat.gz'
  3 cbserial an integer 2017000000061 'input/usa_00007.dat.gz'
... ........ .......... ............. ........................
See problems(...) for more details.
```

**Comment by AaronGullickson** [comment]
@amandavel I believe cluster and cbserial are too large for the default integer values that it read_fwf wants to store them as. The easiest solution would be to leave those variables out as I don't think you need them. Alternatively you can specify that those columns should be read as "doubles", but thats a little trickier.

**Comment by AaronGullickson** [comment]
Also, subtle point, but technically you didn't get an error but a warning. A warning means the command ran, but it may not have done something right so it wants you to be aware. In this case, you probably have all missing values for cbserial and cluster.
